# Generated by Django 4.2.2 on 2023-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diruploadmodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='diruploadmodel',
            name='files',
            field=models.FileField(upload_to='mouse', verbose_name='File'),
        ),
    ]
