# Generated by Django 4.2.2 on 2023-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchanger', '0003_rename_files_diruploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diruploadmodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
