# Generated by Django 4.2.2 on 2023-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchanger', '0004_alter_diruploadmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diruploadmodel',
            name='set_id',
            field=models.CharField(default='sdfghjkjhgfd', editable=False, max_length=32),
        ),
    ]
