# Generated by Django 4.2.2 on 2023-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchanger', '0005_diruploadmodel_set_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diruploadmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='diruploadmodel',
            name='file',
            field=models.FileField(upload_to='mouse'),
        ),
    ]
